# Generated by Django 4.0 on 2021-12-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(help_text='Age in years.', max_length=5, verbose_name='Age')),
                ('gender', models.CharField(help_text='Participant Gender', max_length=6, verbose_name='Gender')),
                ('nationality', models.CharField(help_text='Date and time of report.', max_length=36, verbose_name='Nationality')),
                ('is_literate', models.CharField(help_text='Date and time of report.', max_length=5, verbose_name='Report Date and Time')),
                ('report_datetime', models.DateTimeField(help_text='Date and time of report.', verbose_name='Report Date and Time')),
            ],
            options={
                'verbose_name': 'Screening Eligibility',
                'verbose_name_plural': 'Screening Eligibility',
            },
        ),
    ]
