# Generated by Django 4.0 on 2021-12-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traineeproject_subject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screeningeligibility',
            old_name='age',
            new_name='age_in_years',
        ),
    ]
