# Generated by Django 4.0 on 2021-12-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traineeproject_subject', '0002_rename_age_screeningeligibility_age_in_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEngagementQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(help_text='Participant Gender', max_length=6, verbose_name='Gender')),
                ('report_datetime', models.DateTimeField(help_text='Date and time of report.', verbose_name='Report Date and Time')),
            ],
            options={
                'verbose_name': 'Community Engagement Questionnaire',
                'verbose_name_plural': 'Community Engagement Questionnaire',
            },
        ),
        migrations.CreateModel(
            name='EducationQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(help_text='Participant Gender', max_length=6, verbose_name='Gender')),
                ('report_datetime', models.DateTimeField(help_text='Date and time of report.', verbose_name='Report Date and Time')),
            ],
            options={
                'verbose_name': 'Education Questionnaire',
                'verbose_name_plural': 'Education Questionnaire',
            },
        ),
        migrations.CreateModel(
            name='SubjectConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(help_text='Participant Gender', max_length=6, verbose_name='Gender')),
                ('report_datetime', models.DateTimeField(help_text='Date and time of report.', verbose_name='Report Date and Time')),
            ],
            options={
                'verbose_name': 'Subject Consent',
                'verbose_name_plural': 'Subject Consent',
            },
        ),
        migrations.CreateModel(
            name='SubjectRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(help_text='Participant Gender', max_length=6, verbose_name='Gender')),
                ('report_datetime', models.DateTimeField(help_text='Date and time of report.', verbose_name='Report Date and Time')),
            ],
            options={
                'verbose_name': 'Subject Requisition',
                'verbose_name_plural': 'Subject Requisition',
            },
        ),
    ]
